/**
 * server/__tests__/llm-integration.test.ts
 *
 * Day8+: LLM 集成测试 (有 key 走 LLM 路径, 无 key 走 fallback)
 *
 * 重要性 (上线前必跑):
 *   - 确认 quest/dialogue 生成器有 key 时**真发请求**给 DeepSeek
 *   - 确认 JSON 解析 + cache + error fallback 整条链工作
 *   - 确认 LLM API 失败时不挂服务 (走 fallback)
 *   - 防止 "fallback 静默成功" 蒙混过关 (有 key 必须真发请求)
 *
 * 测试策略:
 *   - 2 个阶段: 有 key (skip) + 无 key (always run)
 *   - 有 key: stubDeepSeek 检测请求是否到达 (不是直接打真 API, 避免 rate limit)
 *   - 无 key: 验证 fallback 路径
 *
 * 用户应:
 *   1. 设 DEEPSEEK_API_KEY env
 *   2. 跑 npm test → LLM 集成测试用 stub, 验证协议对
 *   3. 手动跑 scripts/test-llm-real.ts (真 API) 一次
 */

import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { generateQuest, generateDialogue, isLlmAvailable } from '../../src/core/llm/index.js';
import { fallbackQuest, fallbackDialogue } from '../../src/core/llm/index.js';
import { llmCache, hashKey } from '../../src/core/llm/cache.js';
import { log } from '../../src/core/log.js';

const HAS_KEY = !!process.env.DEEPSEEK_API_KEY;

describe('LLM 集成测试 (上线前必跑)', () => {
  beforeEach(() => {
    llmCache.clear();
  });

  // ============ 无 key: fallback 路径 (永远跑) ============

  describe('无 DEEPSEEK_API_KEY (fallback 路径)', () => {
    it('isLlmAvailable() = false', () => {
      // 临时清掉 key
      const orig = process.env.DEEPSEEK_API_KEY;
      delete process.env.DEEPSEEK_API_KEY;
      try {
        expect(isLlmAvailable()).toBe(false);
      } finally {
        if (orig) process.env.DEEPSEEK_API_KEY = orig;
      }
    });

    it('generateQuest 走 fallback, 不抛错', async () => {
      const orig = process.env.DEEPSEEK_API_KEY;
      delete process.env.DEEPSEEK_API_KEY;
      try {
        const r = await generateQuest(1, 'forest');
        expect(r.meta.source).toBe('fallback');
        expect(r.meta.reason).toContain('DEEPSEEK_API_KEY');
        expect(r.quest.title).toBe(fallbackQuest(1).title);
      } finally {
        if (orig) process.env.DEEPSEEK_API_KEY = orig;
      }
    });

    it('generateDialogue 走 fallback', async () => {
      const orig = process.env.DEEPSEEK_API_KEY;
      delete process.env.DEEPSEEK_API_KEY;
      try {
        const r = await generateDialogue('Lantern Bearer', 'cranky', 'first');
        expect(r.meta.source).toBe('fallback');
        expect(r.dialogue.greeting).toBeTruthy();
      } finally {
        if (orig) process.env.DEEPSEEK_API_KEY = orig;
      }
    });
  });

  // ============ 有 key: 走 LLM 路径 (用 mock 避免真打 API) ============

  describe('有 DEEPSEEK_API_KEY (LLM 路径)', () => {
    // 这个 describe 在 CI/没 key 时也跑, 但 mock fetch 让 generateText 用 fake response
    // 不依赖真 API, 测试协议是否正确 (含 auth/json/etc)
    let mockFetch: ReturnType<typeof vi.fn>;
    const originalEnv = { ...process.env };

    beforeEach(() => {
      mockFetch = vi.fn();
      vi.stubGlobal('fetch', mockFetch);
      process.env.DEEPSEEK_API_KEY = 'sk-test-12345';
    });

    afterEach(() => {
      vi.unstubAllGlobals();
      process.env = { ...originalEnv };
    });

    it('isLlmAvailable() = true', () => {
      expect(isLlmAvailable()).toBe(true);
    });

    it('generateQuest 真发 fetch 请求到 DeepSeek', async () => {
      const llmJson = JSON.stringify({
        title: 'LLM Test Quest',
        description: 'Generated by mock LLM',
        objective: 'verify the LLM path',
        reward: '1 test point',
      });
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: llmJson } }] }),
        text: async () => llmJson,
      } as unknown as Response);

      const r = await generateQuest(1, 'forest');
      expect(r.meta.source).toBe('llm'); // 关键: 不是 fallback
      expect(r.quest.title).toBe('LLM Test Quest');
      // fetch 必须被调 (即真发了 HTTP 请求, 而不是 fallback)
      expect(mockFetch).toHaveBeenCalledOnce();
    });

    it('generateQuest 验证 fetch URL 是 DeepSeek chat completions', async () => {
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: '{}' } }] }),
        text: async () => '{}',
      } as unknown as Response);

      await generateQuest(1, 'forest');
      const [url, init] = mockFetch.mock.calls[0];
      // URL 含 /chat/completions + Bearer auth
      expect(String(url)).toMatch(/\/chat\/completions$/);
      const headers = init.headers as Record<string, string>;
      expect(headers.Authorization).toBe('Bearer sk-test-12345');
      // body 含 jsonMode
      const body = JSON.parse(init.body);
      expect(body.response_format).toEqual({ type: 'json_object' });
    });

    it('generateDialogue 走 LLM 路径', async () => {
      const llmJson = JSON.stringify({
        greeting: 'LLM Greeting',
        hint: 'LLM Hint',
        farewell: 'LLM Farewell',
      });
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: llmJson } }] }),
        text: async () => llmJson,
      } as unknown as Response);

      const r = await generateDialogue('Test NPC', 'wise', 'ctx');
      expect(r.meta.source).toBe('llm');
      expect(r.dialogue.greeting).toBe('LLM Greeting');
    });

    it('LLM 返 401 → 立即 fallback (不重试)', async () => {
      mockFetch.mockResolvedValue({
        ok: false,
        status: 401,
        json: async () => ({ error: 'invalid api key' }),
        text: async () => 'invalid api key',
      } as unknown as Response);

      const r = await generateQuest(1, 'forest');
      expect(r.meta.source).toBe('fallback');
      expect(r.meta.reason).toContain('401');
      // 401 不重试, fetch 只调 1 次
      expect(mockFetch).toHaveBeenCalledTimes(1);
    });

    it('LLM 返 500 → 重试 3 次后 fallback', async () => {
      for (let i = 0; i < 3; i++) {
        mockFetch.mockResolvedValueOnce({
          ok: false,
          status: 500,
          json: async () => ({ error: 'server error' }),
          text: async () => 'server error',
        } as unknown as Response);
      }

      const r = await generateQuest(1, 'forest');
      expect(r.meta.source).toBe('fallback');
      // 3 次重试后 throw
      expect(mockFetch).toHaveBeenCalledTimes(3);
    }, 10_000);

    it('LLM 返 429 → 重试 3 次后 fallback', async () => {
      for (let i = 0; i < 3; i++) {
        mockFetch.mockResolvedValueOnce({
          ok: false,
          status: 429,
          json: async () => ({ error: 'rate limited' }),
          text: async () => 'rate limited',
        } as unknown as Response);
      }
      const r = await generateQuest(1, 'forest');
      expect(r.meta.source).toBe('fallback');
      expect(mockFetch).toHaveBeenCalledTimes(3);
    }, 10_000);

    it('LLM 返坏 JSON → fallback (解析失败)', async () => {
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: 'not valid json {' } }] }),
        text: async () => 'not valid json {',
      } as unknown as Response);

      const r = await generateQuest(1, 'forest');
      expect(r.meta.source).toBe('fallback');
    });

    it('LLM 缓存: 相同 (level, biome) 第二次返 cache', async () => {
      const llmJson = JSON.stringify({
        title: 'Cached Quest', description: 'd', objective: 'o', reward: 'r',
      });
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: llmJson } }] }),
        text: async () => llmJson,
      } as unknown as Response);

      const r1 = await generateQuest(2, 'mountain');
      const r2 = await generateQuest(2, 'mountain');
      expect(r1.meta.source).toBe('llm');
      expect(r2.meta.source).toBe('cache');
      expect(mockFetch).toHaveBeenCalledTimes(1); // 缓存命中不重发
    });

    it('LLM cache key 含 level + biome + system prompt hash (避免跨请求污染)', async () => {
      const llmJson = JSON.stringify({ title: 'X', description: 'd', objective: 'o', reward: 'r' });
      mockFetch.mockResolvedValue({
        ok: true,
        status: 200,
        json: async () => ({ choices: [{ message: { content: llmJson } }] }),
        text: async () => llmJson,
      } as unknown as Response);

      await generateQuest(1, 'forest');
      await generateQuest(2, 'forest');
      await generateQuest(1, 'swamp');
      // 3 个不同 input → 3 次 fetch
      expect(mockFetch).toHaveBeenCalledTimes(3);
    });
  });

  // ============ 真实 key: 手动跳过 (避免 rate limit) ============

  describe.skipIf(!HAS_KEY)('有真 key: 端到端真实 LLM (手动跑)', () => {
    it('generateQuest 真发请求 → 返 LLM 内容 (json_mode)', async () => {
      const r = await generateQuest(1, 'forest');
      // 来源不一定是 llm (可能 cache), 但 quest 应是 LLM 风格
      expect(r.quest.title).toBeTruthy();
      expect(r.quest.title.length).toBeGreaterThan(2);
      expect(r.quest.description).toBeTruthy();
      expect(r.quest.objective).toBeTruthy();
      expect(r.quest.reward).toBeTruthy();
    }, 30_000); // 30s 超时 (网络往返)
  });
});

describe('LLM 集成端到端: server 端 /dialogue 端点', () => {
  // 跳过环境问题, 单独测
  it('对话生成不抛错 (fallback 一定走通)', async () => {
    const r = await generateDialogue('Lantern Bearer', 'cranky', 'first visit');
    expect(r.dialogue.greeting).toBeTruthy();
    expect(r.dialogue.farewell).toBeTruthy();
  });
});

describe('LLM 安全: 日志不泄露 key', () => {
  it('log.* 不打印 DEEPSEEK_API_KEY', () => {
    // 截 log 输出, 验证不含 key
    const orig = process.env.DEEPSEEK_API_KEY;
    process.env.DEEPSEEK_API_KEY = 'sk-secret-key-12345';
    const logSpy = vi.spyOn(console, 'log').mockImplementation(() => {});
    const errSpy = vi.spyOn(console, 'error').mockImplementation(() => {});
    try {
      // 触发一些 log
      log.info('test message');
      // 验证 spy 没有被调用 'sk-secret'
      const allCalls = [...logSpy.mock.calls, ...errSpy.mock.calls].flat().join(' ');
      expect(allCalls).not.toContain('sk-secret');
    } finally {
      logSpy.mockRestore();
      errSpy.mockRestore();
      if (orig) process.env.DEEPSEEK_API_KEY = orig;
      else delete process.env.DEEPSEEK_API_KEY;
    }
  });
});
